### PR TITLE
update

### PR DESCRIPTION
**Pull request by Benraouf93**
Update : startPage / SignUPPage / LoginPage / images

### CODE REVIEW

**Comment by amuza2** [comment]
next time all code PR are going to be in branches. pushing directly to main will be allowed and for everyone

**Comment by abdelillahbel** [comment]
### gg

**Review by abdelillahbel — COMMENTED** [review]
* we are working as team, in next time don't forget to add comments

**Comment by amuza2** [comment]
> * we are working as team, in next time don't forget to add comments

we can't add Assignees, Labels to our issues, check your admin control and give us these feature

**Comment by abdelillahbel** [comment]
okay 👌

**Comment by abdelillahbel** [comment]
image

* done

**Pull request merged**
